### ISSUE TITLE
Не закоммитилась страница

### ISSUE THREAD

**Issue by Event-ITP** [pyconru/pycon.ru#56]
Внесла изменения сюда https://github.com/pyconru/pycon.ru/tree/carcade/pages/participation/hotels, но на сайте не обновилось. Что я делаю не так? :)

**Comment by mkalininait** [comment]
Привет, IT-People. 
Я посмотрела историю коммитов. Мне кажется, все изменения данной страницы присутствуют сейчас на сайте. 
Также важно понимать, что сайт обновляется не мгновенно после каждого коммита, а примерно раз в 5 минут. Может быть, проблема в этом? )

**Comment by mkalininait** [comment]
Если проблемы и правда нет, то закройте issue, пожалуйста.
